name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check code formatting
        run: npm run format:check
      
      - name: Run linting
        run: npm run lint
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Run tests
        run: npm run test:ci
      
      - name: Test CLI functionality
        run: |
          echo "Testing CLI with AI-like file (should exit with code 1)..."
          set +e  # Don't exit on non-zero exit codes
          npx . test/fixtures/ai-like.md
          AI_LIKE_EXIT_CODE=$?
          set -e
          
          echo "Testing CLI with clean file (should exit with code 0)..."
          npx . test/fixtures/clean.md
          CLEAN_EXIT_CODE=$?
          
          echo "Testing JSON output..."
          set +e
          npx . test/fixtures/ai-like.md --json > test-output.json
          set -e
          echo "JSON output generated successfully"
          
          # Verify exit codes
          if [ $AI_LIKE_EXIT_CODE -eq 1 ]; then
            echo "✅ AI-like file test passed (exit code 1 as expected)"
          else
            echo "❌ AI-like file test failed (expected exit code 1, got $AI_LIKE_EXIT_CODE)"
            exit 1
          fi
          
          if [ $CLEAN_EXIT_CODE -eq 0 ]; then
            echo "✅ Clean file test passed (exit code 0 as expected)"
          else
            echo "❌ Clean file test failed (expected exit code 0, got $CLEAN_EXIT_CODE)"
            exit 1
          fi